/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubscriptionPlan = IDL.Variant({
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProposalInput = IDL.Record({
  'portfolioLink' : IDL.Text,
  'experienceLevel' : IDL.Text,
  'skills' : IDL.Text,
  'clientJobDescription' : IDL.Text,
});
export const ProposalOutput = IDL.Record({
  'shortDmPitch' : IDL.Text,
  'coldEmailPitch' : IDL.Text,
  'upworkFreeProposal' : IDL.Text,
  'pricingBreakdown' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'plan' : SubscriptionPlan,
  'remainingFreeGenerations' : IDL.Nat,
  'totalGenerations' : IDL.Nat,
});
export const Time = IDL.Int;
export const SavedProposal = IDL.Record({
  'id' : IDL.Nat,
  'output' : ProposalOutput,
  'userId' : IDL.Principal,
  'timestamp' : Time,
  'input' : ProposalInput,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminGetUserSubscriptionStatus' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Opt(
          IDL.Record({
            'plan' : SubscriptionPlan,
            'remainingFreeGenerations' : IDL.Nat,
            'totalGenerations' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProposal' : IDL.Func([IDL.Nat], [], []),
  'generateProposal' : IDL.Func(
      [ProposalInput, ProposalOutput],
      [ProposalOutput],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProposalById' : IDL.Func([IDL.Nat], [IDL.Opt(SavedProposal)], ['query']),
  'getSavedProposals' : IDL.Func([], [IDL.Vec(SavedProposal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubscriptionStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'plan' : SubscriptionPlan,
          'remainingFreeGenerations' : IDL.Nat,
          'totalGenerations' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProposal' : IDL.Func([ProposalInput, ProposalOutput], [IDL.Nat], []),
  'upgradeToPremium' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubscriptionPlan = IDL.Variant({
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProposalInput = IDL.Record({
    'portfolioLink' : IDL.Text,
    'experienceLevel' : IDL.Text,
    'skills' : IDL.Text,
    'clientJobDescription' : IDL.Text,
  });
  const ProposalOutput = IDL.Record({
    'shortDmPitch' : IDL.Text,
    'coldEmailPitch' : IDL.Text,
    'upworkFreeProposal' : IDL.Text,
    'pricingBreakdown' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'plan' : SubscriptionPlan,
    'remainingFreeGenerations' : IDL.Nat,
    'totalGenerations' : IDL.Nat,
  });
  const Time = IDL.Int;
  const SavedProposal = IDL.Record({
    'id' : IDL.Nat,
    'output' : ProposalOutput,
    'userId' : IDL.Principal,
    'timestamp' : Time,
    'input' : ProposalInput,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminGetUserSubscriptionStatus' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Opt(
            IDL.Record({
              'plan' : SubscriptionPlan,
              'remainingFreeGenerations' : IDL.Nat,
              'totalGenerations' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProposal' : IDL.Func([IDL.Nat], [], []),
    'generateProposal' : IDL.Func(
        [ProposalInput, ProposalOutput],
        [ProposalOutput],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProposalById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SavedProposal)],
        ['query'],
      ),
    'getSavedProposals' : IDL.Func([], [IDL.Vec(SavedProposal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubscriptionStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'plan' : SubscriptionPlan,
            'remainingFreeGenerations' : IDL.Nat,
            'totalGenerations' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProposal' : IDL.Func([ProposalInput, ProposalOutput], [IDL.Nat], []),
    'upgradeToPremium' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };