/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ProposalInput {
  'portfolioLink' : string,
  'experienceLevel' : string,
  'skills' : string,
  'clientJobDescription' : string,
}
export interface ProposalOutput {
  'shortDmPitch' : string,
  'coldEmailPitch' : string,
  'upworkFreeProposal' : string,
  'pricingBreakdown' : string,
}
export interface SavedProposal {
  'id' : bigint,
  'output' : ProposalOutput,
  'userId' : Principal,
  'timestamp' : Time,
  'input' : ProposalInput,
}
export type SubscriptionPlan = { 'premium' : null } |
  { 'free' : null };
export type Time = bigint;
export interface UserProfile {
  'plan' : SubscriptionPlan,
  'remainingFreeGenerations' : bigint,
  'totalGenerations' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminGetUserSubscriptionStatus' : ActorMethod<
    [Principal],
    [] | [
      {
        'plan' : SubscriptionPlan,
        'remainingFreeGenerations' : bigint,
        'totalGenerations' : bigint,
      }
    ]
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProposal' : ActorMethod<[bigint], undefined>,
  'generateProposal' : ActorMethod<
    [ProposalInput, ProposalOutput],
    ProposalOutput
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProposalById' : ActorMethod<[bigint], [] | [SavedProposal]>,
  'getSavedProposals' : ActorMethod<[], Array<SavedProposal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubscriptionStatus' : ActorMethod<
    [],
    {
      'plan' : SubscriptionPlan,
      'remainingFreeGenerations' : bigint,
      'totalGenerations' : bigint,
    }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProposal' : ActorMethod<[ProposalInput, ProposalOutput], bigint>,
  'upgradeToPremium' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];